#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os

def _is_in_devel():
    SCRIPTS_DIR = "scripts"
    d = os.path.split(os.path.dirname(os.path.abspath(__file__)))[1]
    return d == SCRIPTS_DIR


if __name__ == "__main__":
    if _is_in_devel():
        d = os.path.split(os.path.dirname(os.path.abspath(__file__)))[0]
        sys.path.insert(0, d)
    from mapmap.control import runner

    runner.run()

